-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 10:39:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chapter` (
  `id_chapter` INT NOT NULL,
  `name_chapter` VARCHAR(100) NOT NULL,
  `id_subchapter` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_chapter`),
  INDEX `fk_Chapter_Chapter_idx` (`id_subchapter` ASC) VISIBLE,
  CONSTRAINT `fk_Chapter_Chapter`
    FOREIGN KEY (`id_subchapter`)
    REFERENCES `mydb`.`Chapter` (`id_chapter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id_user` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `email` VARCHAR(80) NULL,
  `pass` VARCHAR(45) NULL,
  `is_auhtor` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `id_tag` INT NOT NULL,
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rating` (
  `id_rating` INT NOT NULL,
  `grade` TINYINT NOT NULL,
  PRIMARY KEY (`id_rating`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `id_comment` INT NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_comment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publications` (
  `id_publications` INT NOT NULL,
  `title` VARCHAR(72) NOT NULL,
  `announcement` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `Chapter_id_chapter` INT NOT NULL,
  PRIMARY KEY (`id_publications`),
  INDEX `fk_Publications_Chapter1_idx` (`Chapter_id_chapter` ASC) VISIBLE,
  CONSTRAINT `fk_Publications_Chapter1`
    FOREIGN KEY (`Chapter_id_chapter`)
    REFERENCES `mydb`.`Chapter` (`id_chapter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserComms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserComms` (
  `id_user` INT NOT NULL,
  `id_comment` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_comment`),
  INDEX `fk_table1_Comment1_idx` (`id_comment` ASC) VISIBLE,
  CONSTRAINT `fk_table1_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Comment1`
    FOREIGN KEY (`id_comment`)
    REFERENCES `mydb`.`Comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PublicationTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PublicationTags` (
  `id_publications` INT NOT NULL,
  `id_tag` INT NOT NULL,
  PRIMARY KEY (`id_publications`, `id_tag`),
  INDEX `fk_PublicationTags_Tag1_idx` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `fk_PublicationTags_Publications1`
    FOREIGN KEY (`id_publications`)
    REFERENCES `mydb`.`Publications` (`id_publications`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PublicationTags_Tag1`
    FOREIGN KEY (`id_tag`)
    REFERENCES `mydb`.`Tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AuthorsWithRatingPublications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AuthorsWithRatingPublications` (
  `id_user` INT NOT NULL,
  `id_publications` INT NOT NULL,
  `Rating_id_rating` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_publications`, `Rating_id_rating`),
  INDEX `fk_AuthorsPublications_Publications1_idx` (`id_publications` ASC) VISIBLE,
  INDEX `fk_AuthorsPublications_Rating1_idx` (`Rating_id_rating` ASC) VISIBLE,
  CONSTRAINT `fk_AuthorsPublications_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AuthorsPublications_Publications1`
    FOREIGN KEY (`id_publications`)
    REFERENCES `mydb`.`Publications` (`id_publications`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AuthorsPublications_Rating1`
    FOREIGN KEY (`Rating_id_rating`)
    REFERENCES `mydb`.`Rating` (`id_rating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
